# -*- coding: utf-8 -*-
"""Challenge.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PYTwkgqCDOcfHH9jjx1nwsgBHyHNZ6pf
"""

import pandas as pd
import numpy as np
!pip install flask
!pip install fastapi uvicorn sqlalchemy pandas

from flask import Flask

df_departments=pd.read_csv('/content/departments.csv')
df_departments

df_employees=pd.read_csv('/content/hired_employees.csv')
df_employees

df_jobs=pd.read_csv('/content/jobs.csv')
df_jobs

"""1. After install the libraries, we create an instance of the Flask class. WSGI application"""

WSGI= Flask(__name__)